# Generated by Django 4.2.5 on 2023-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('queue_name', models.CharField(max_length=50)),
                ('task_id', models.CharField(max_length=300)),
            ],
        ),
    ]
